### ISSUE TITLE
error with midori database access

### ISSUE THREAD

**Issue by mimouschka** [xapple/crest4#3]
Hi,
I have installed crest4 through conda, and managed to successfully change the CREST4_DIR to a common folder by adding its path on my .bashrc file using:

export CREST4_DIR=/path/to/common/folder

Now, when I run crest4 --pytest

I get the following error:

FAILED conda/crest4/lib/python3.11/site-packages/crest4/tests/midori_test/run_test.py::test_midori - requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://crest4.s3-eu-west-1.amazonaws.com/midori253darn.tar.gz

Indeed, there is only silvamod138pr2 in the CREST4_DIR. How do I get access to MIDORI?

**Comment by xapple** [comment]
Hi,
I should have a fix coming for this very soon. I will update the ticket when the issue is resolved.

**Comment by xapple** [comment]
If you update `crest4` to the latest version, the midori database should now be working. Please report if this is still not the case. Thanks.

**Comment by mimouschka** [comment]
After running 
conda update -c bioconda -c conda-forge -c xapple crest4

I have crest4 version 4.3.2 and am still running into these issues with crest4 --pytest:

FAILED crest4/lib/python3.11/site-packages/crest4/tests/db_midori/run_test.py::test_db_midori - assert 'Saccharomyces' == "'Saccharomyces'"
FAILED crest4/lib/python3.11/site-packages/crest4/tests/db_mitofish/run_test.py::test_db_mitofish - AssertionError: assert 'Luciogobius guttatus' == 'Lorem ipsum'

I see in your commits from today that you might have fixed the Saccharomyces issue... should I update again tomorrow and see if the conda update command updates to the latest version (maybe there are some time delays)?

**Comment by xapple** [comment]
Yeah as you have noticed, in fact I'm still working on it and fixing some stuff. Should be stable soon.

**Comment by xapple** [comment]
OK all tests should be passing now.

**Comment by mimouschka** [comment]
yes, all good now ! thanks!
