### ISSUE TITLE
Using BOLD database with CREST4

### ISSUE THREAD

**Issue by Enorya** [xapple/crest4#4]
Dear,

I'm new to the use of CREST4 and I would like to use it to classify COI sequences. I saw in the previous version of CREST that it was possible to use BOLD as a reference database. However, with CREST4, I don't see this possibility.

Are you planning to add the BOLD database in the already implemented reference databases? 

If not, can you explain me which is the easiest way to download the BOLD database myself and use it in CREST4?

I already downloaded the BOLD database for an other project with [CRABS](https://github.com/gjeunen/reference_database_creator) but the format seems to not fit the requirements of the [make_new_crest_db.py](https://github.com/xapple/crest4_utils/blob/master/dev_scripts/make_new_crest_db.py) because there is no accession numbers (see example below).
```
CRABS_1:Megascolecidae  6400    Eukaryota       Annelida        Clitellata      Crassiclitellata        Megascolecidae  nan     nan     AACCTTATATTTTCTTTTAGGAATTTGAGCTGGAATAGTTGGTGCCGGAATAAGTTTACTTATCCGCATTGAATTAAGACAGCCGGGTGCATTTCTAGGCAGTGATCAACTATATAATACTTTAGTAACAGCTCACGCATTCGTAATAATTTTCTTTATGGTTATACCCGTATTTATTGGAGGATTTGGTAATTGACTCCTTCCACTAATATTAGGTGCCCCAGACATAGCATTCCCTCGCCTAAACAACCTAAGATTTTGATTATTACCGCCATCCTTAATTCTATTAGTCTCATCTGCAGCAGTAGAAAAAGGCGCCGGTACAGGATGAACAGTTTATCCTCCTTTAGCTAGAAATATAGCTCATGCAGGACCTTCTGTAGACCTAGCAATCTTCTCCCTCCATCTAGCAGGCGCATCCTCAATTTTAGGAGCATTAAACTTCATTACTACAGTTATTAACATACGTTGACAAGGTCTACGACTCGAGCGAATCCCACTATTTGTTTGAGCCGTTACTATTACAGTAGTATTACTACTTTTATCTTTACCAGTATTAGCTGGTGCAATTACCATATTATTAACCGACCGAAACTTAAACACATCTTTCTTTGATCCAGCGGGAGGGGGAGACCCTATTCTTTATCAACATTTATTC
CRABS_2:Nais    85919   Eukaryota       Ascomycota      Sordariomycetes Microascales    Halosphaeriaceae        Nais    nan     TACACTATATCTTATCTTAGGAGTATGAGCAGGAATAGTAGGAACTGGAACTAGATTACTTATTCGAATTGAATTATCACAACCAGGATCATTTCTTGGAAGAGATCAATTATATAATACTCTTGTAACAGCACATGCATTCTTAATAATTTTCTTCTTAGTAATACCAGTATTCATTGGGGGGTTCGGAAACTGACTTCTCCCATTAATACTAGGTGCTGCTGATATGGCATTTCCACGACTAAATAATCTTAGATTTTGACTACTACCACCATCATTAATTCTATTAATTTCTTCTGCTGCTGTAGAAAAAGGTGCGGGAACAGGATGAACTGTTTATCCTCCACTATCAAGAAACCTGGCACATGCAGGACCTTCAGTAGACATGGCTATTTTCTCACTCCATTTAGCAGGTGCTTCTTCTATTTTAGGGGCAGTTAACTTTATCACTACTGTAATAAACATGCGATGAAACGGAATACGATTAGAACGACTTCCACTATTTGTGTGAGCGGTATTTCTCACAGTAATTCTCCTTCTTCTATCACTTCCTGTTCTTGCTGGCGCAATTACAATACTACTAACAGATCGAAACCTTAATACCTCATTCTTCGATCCTGCTGGTGGTGGAGACCCAATTTTATATCAACATTTATTC
```

**Comment by xapple** [comment]
To classify COI sequences, it is recommended to use the `midori253darn` database which effectively replaces the old `bold` database.

https://www.reference-midori.info/index.html

**Comment by xapple** [comment]
> As opposed to BOLD, Midori also has some bacterial sequences, but these are for removing non-target amplification of mitochondrial COI analogs in bacteria. It also has more protist and algae sequences than BOLD and is more inclusive, though possibly less taxonomically revised for some branches. Overall, the benefits outweigh BOLD that was based on an earlier version and it was possibly not allowed to re-distribute as we used to do, due to some license issues.

**Comment by Enorya** [comment]
Thank you for your quick reply!
I will use the Midori database.
